- web/concrete/core/libraries/content/importer.php
Add ability to import user and public date same as 5.7 ContentImporter
> Enhancement importing page structure

- web/concrete/core/helpers/date.php
Fix the logical comparison error in Date helper formatDate method
> Fix logical error

- web/concrete/core/helpers/form/date_time.php
Bugtracker: http://www.concrete5.org/developers/bugs/5-6-3-2/saved-ampm-date-attributedoes-not-loaded-on-the-panel/
> Fix datepicker bug in non US languages

- web/concrete/core/helpers/image.php
We cant crop gif images with Imagick
See: http://php.net/manual/en/imagick.cropthumbnailimage.php#106710
> Gif cropping not works with Imagick

- web/concrete/tools/newsflow.php
We can not read Newsflow now. Let's make it works again.
> Make news flow work again

- web/concrete/mail/user_register.php
fix typo
reported by Takashi Ando @andotake3
> Fix typo in user_register.php

- web/concrete/startup/process.php
Resolved this problem: https://www.concrete5.org/developers/bugs/5-6-3-2/pagelist-filterbyattribute-get-wrong-results/
> Update SearchIndex on edit page attributes

- web/concrete/helpers/concrete/upgrade/version_5633.php
* Refresh updated table
* Update the robotx.txt rules
We are discussing about new robots.txt rule at here: #1865
> Update 5633 upgrade script

- web/concrete/core/libraries/view.php
it's not possible to override the file permissions mode without this change
> use proper constant to get file permissions mode

- web/concrete/core/libraries/block_view_template.php
replaces https://github.com/concrete5/concrete5/pull/1871
> static block template path fixed

- web/concrete/core/controllers/blocks/image.php
* Can't save the `forceImageToMatchDimensions` value
* Can't get the size of the hover image
> Bug fixes to Image block

- web/concrete/core/models/page.php
https://github.com/concrete5/concrete5/pull/1833
> remove useless Insert_ID

- web/concrete/elements/block_footer_edit.php
URL Encode value since it's used in URL
> Prevent possible XSS

- web/concrete/blocks/form/view.php
Useful to hide/style forms after submissions
> Add css class to Form block view to signal submission state

- web/concrete/single_pages/dashboard/extend/install.php
I got fed up with trawling through long and un-sorted lists of packages.
> Sort the installed package list to make it easier to work with

- web/concrete/core/models/page.php
> Mark as static the Page::queueFor...Sort methods

- web/concrete/core/helpers/validation/strings.php
- web/concrete/libraries/3rdparty/is_email.php
> use is_email to support multibyte domains in email addresses

- web/concrete/core/models/userinfo.php
> fix message ID when adding sender/recipient

- web/concrete/core/controllers/blocks/form.php
> Check if FORM_BLOCK_SENDER_EMAIL is defined

- web/concrete/core/controllers/blocks/image.php
fixes https://github.com/concrete5/concrete5-legacy/issues/1997
> fix image block export

- web/concrete/js/jquery.form.js
fixes https://github.com/concrete5/concrete5-legacy/issues/2000
> fix ajax requests for chrome 83

- web/concrete/core/models/permission/keys/custom/access_user_search.php
Fixes https://github.com/concrete5/concrete5-legacy/issues/1980
> Escape another occurence of reserved word Groups
