web/concrete/core/models/permission/assignments/block.php

This is the fix for the same problem as concrete5/concrete5-5.7.0#1789

Double check whether the Area overrides the collection permission

---

web/concrete/tools/permissions/categories/admin.php
web/concrete/tools/permissions/categories/file.php
web/concrete/tools/permissions/categories/user.php

I'm working on the job that extend Workflow. It is able to attach Workflows for Page Permissions, but it is not able to attach custom Workflows for other permission categories. This request might fix this issue, but I'd like to hear the opinion from core team.

Enables to attach Workflows for Task/User/File permissions

---

web/concrete/core/libraries/cache.php

not quite sure if this is really the way to go, but we often had caching problems not only related to concrete5 but also to APC. Especially when updating existing files we thought that there's a problem with the environment cache while in reality it was APC.

clear APC cache when flushing concrete5 cache

---

web/concrete/single_pages/dashboard/reports/logs.php

Cherry-picked a fix from 5.7 repository.
- if a user is deleted, we call a method on a NULL: let's avoid it
- getUserID may return '0': comparing with NULL returns false
(see http://mlocati.github.io/php-comparisions/)

Fix log view when user id is '0' or deleted users

---

build/package.json

`npm install` doesn't seem to work anymore, repository info added

add repository item to satisfy npm 1.2.20

---

web/robots.txt

this makes sure the robots.txt of a new installation matches the one from an upgraded site https://github.com/concrete5/concrete5/pull/1886

block xml and php in robots.txt

---

web/concrete/helpers/concrete/upgrade/version_5633.php

CSS and JS files in the themes directory must be accessible to let google render a page properly

remove /themes from robots.txt

---

web/concrete/core/controllers/single_pages/dashboard/composer/write.php

When composer saves a draft, it uses the "system" (server) timezone to translate the "Public Date" field. If the system timezone differs from the app or user timezone, it results in the time being saved differently than it was entered. In order to correct this, pass the resulting converted timezone through the date helper's `getSystemDateTime` function. This is how these dates are handled when saving page properties from the frontend: https://github.com/concrete5/concrete5/blob/629e95fd4ccfd63f7bd2444e8e77faa8f0b432c4/web/concrete/startup/process.php#L1036

Fix incorrect public date when composer drafts are saved

---

web/concrete/blocks/form/db.xml

this query is super slow https://github.com/concrete5/concrete5/blob/master/web/concrete/core/controllers/blocks/form.php#L504
you only need about 100'000 entries to make it run for about a minute..

index asID in form answers

---

web/concrete/config/base.php
web/concrete/config/db.xml
web/concrete/libraries/3rdparty/adodb/drivers/adodb-mysqli.inc.php
web/concrete/libraries/3rdparty/adodb/perf/perf-mysqli.inc.php

This replaces #1827.
Fixes to the 'mysqli' DB_TYPE. No need to make it transactional since it already is. I was previously mislead by the comment in the 'mysqli' db driver, so I removed that as well.
Also added the "perf" library for the mysqli driver.
This also ensures that the mysqli extension is available before setting the DB_TYPE to 'mysqli'. If it's not available, the fallback will be to the old 'mysqlt' DB_TYPE.

'mysqli' DB_TYPE fixes and setting it as the default DB_TYPE if the mysqli extension is available.

---

web/concrete/js/ccm_app/sitemap.js

I believe this was overriding the display_mode passed into the function? _Or is it always **full**?_
Either way, Flagged by **ZBBLOCK** as a Nesting attack (QUN-025) - http://www.spambotsecurity.com/zbblock.php

Removed redundant &display_mode=full

---

web/concrete/core/jobs/remove_old_page_versions.php

This might be a critical issue. The remove old page versions job removes recent 10 page versions.
This is the same issue as concrete5/concrete5-5.7.0#1995 , but we have this bug in 5.6 repo since 2 years ago... :disappointed_relieved: 
392c2534e4d57076f191e381cd0da75f021e735a

Fix remove old page versions job

---

web/concrete/core/helpers/image.php

I believe this along with #1895 will help address https://www.concrete5.org/developers/bugs/5-6-3-3/image-block-scale-image-setting-not-working/

fix image helper resizing

---

web/concrete/core/models/page.php

We use the mysqli driver for transactional support and I run into small issues with Concrete5 every now and then.  Here is the latest:
$newCID is retrieved in the original insert (line 505) and doesn't need to be overwritten.  Calling $db->Insert_ID() with the mysqli driver on that type of query (line 514) returns 0, which causes a problem with PageStatistics::incrementParents and movePageDispayOrdertoBottom().
I've submitted a couple of these changes before under NazWeb@Concrete5.org.

Remove redundant $db->Insert_ID call

---

web/concrete/core/controllers/single_pages/dashboard/extend/install.php

`The package type has been uninstalled`: what's a `package type`? I guess it should be just `package`

'Package type' should be 'Package'

---

web/concrete/js/tiny_mce/themes/advanced/js/source_editor.js
web/concrete/js/tiny_mce/themes/concrete/js/source_editor.js

Bugtracker: www.concrete5.org/developers/bugs/5-6-3-3/tinymce-source-view-html-button-empty-as-of-chrome-43.0.2357.65/

Fix editing HTML in Chrome

---

web/concrete/startup/process.php

Alters a previous pull from @LyDiaMo to reindex the new page version (`$nvc`, which is `$c->getVersionToModify()`), rather than the collection itself (`$c`).

ReIndex page version on attribute save

---

web/concrete/core/helpers/image.php

Assuming we've got a picture with a dimension of 1400x480.
If we wanted to create a thumbnail with a maximum width of 250 the height would have to be 85.714 pixels. That of course won't work, we'll have to either round it up or down. If we specify `bestfit = true` imagick will create a thumbnail with a size of 247x85.
If you show that in a single column you'll quickly see that the pictures have a different width. I get that in some cases you'd want to use the best ratio to get the best quality, but I don't think it's the right thing to do in a CMS.

remove bestfit when creating thumbnails with imagick

---

web/concrete/core/controllers/single_pages/install.php

@ahukkanen we need this too in order to actually use what you did here https://github.com/concrete5/concrete5-legacy/pull/1828, don't we?

allow mysqli instead of mysql when installing concrete5

---

web/concrete/core/controllers/single_pages/install.php

fixes this problem http://www.concrete5.org/developers/bugs/5-6-3-4/5.6.3.4-installation-with-a-title-containing-a-single-quote-char/

escape single quote in site title during installation

---

web/concrete/core/models/attribute/types/select.php

The SelectPeriodAttributeTypeOption::add returns null if we don't save Insert_ID() to a variable first. I think it's because of the mysqli change in C5634.

Fix Insert_ID in SelectAttributeTypeOption

---

web/concrete/core/libraries/request.php

With Apache 2.4.17, REDIRECT_URL contains the domain name and the query string: let's strip them out.
See http://www.concrete5.org/developers/bugs/5-6-3-4/every-page-returns-page-not-found-except-home-page-with-pretty-u/#782956

Fix REDIRECT_URL handling under Apache 2.4.17

---

web/concrete/core/models/permission/access/entity/types/group_set.php

Fix for https://www.concrete5.org/developers/bugs/5-6-3-4/500-error-attempting-to-assign-a-group-set-to-pages-in-5.6.3.4/

Fix selecting group set when assigning advanced permissions

---

web/concrete/core/helpers/lists/states_provinces.php

Quite unbelievably: this typo has been there since [2009-09-08](https://github.com/concrete5/concrete5-legacy/commit/ec45c6bbcfa3ae6ea8062fb54cd2ef7bc89e6fa4#diff-4e657b13dc28140874bf76211deff574R231) :wink:

Fix Brazilian state name Tocatins -> Tocantins

---

web/concrete/core/controllers/blocks/autonav.php

The `getNavigationArray` method is responsible for populating the array of navigation items. Later, in `getNavItems` method, the controller goes through each navigation item and excludes the pages based on certain conditions. This approach is not good as it fetches all the pages and for each page separate database queries are made (i.e. for fetching page object using `Page::getByID`). Hence, there is a possibility that the menu on front end displays only 10 items, but in the back end more than 2000 queries are being made (for e.g., there is a page called Projects under Home which is set to exclude all the sub-pages from nav having 2000 pages under it of page type Project) just for that instance of Auto-Nav block.
This commit adds additional checks in the beginning of `getNavigationArray` …

Updated Auto-Nav block controller to minimize database queries

---

web/concrete/js/tiny_mce/themes/concrete/editor_template.js

Fixes this issue: https://www.concrete5.org/developers/bugs/5-6-3-4/tinymce-format-dropdown-not-showing-selection-format
by applying this change from an old TinyMCE version: https://github.com/tinymce/tinymce/commit/b50e7199cc49a4f4164e0f0d5790c93d691e1f71

Fixed bug where format drop down list wouldn't show the currently active format for a parent element

---

web/concrete/core/models/file_version.php

We have the `on_file_version_add` event that we can use to process a new file added to concrete5, but we miss an event to process new files that replace existing concrete5 versions. What about adding a new `on_file_version_replaced` event?

Add on_file_version_replaced event

---

web/concrete/core/helpers/form.php

We have a number of cases where the third parameter of `submit` is an empty string `''` . That causes an illegal offset warning. It would be nice if that wouldn't happen anywhere and we should fix it there, but this might be the easier and quicker band-aid.
Here's an example https://github.com/concrete5/addon_internationalization/blob/master/packages/multilingual/single_pages/dashboard/multilingual/page_report.php#L74

convert empty string to array due to bad usages

---

web/concrete/core/libraries/localization.php

Had a site with `en_GB` in the multilingual add-on, but somehow Zend failed with `Error opening translation file ''.`. Didn't debug it all the way through, but this seems to work and probably also has the benefit of being faster. This only happens with version 5.6.4.

don't try to load languages that don't exist anymore

---

web/concrete/core/controllers/blocks/autonav.php

https://github.com/concrete5/concrete5-legacy/pull/1934 added an optimization, but the `$ignore_exclude_nav` parameter from `getNavItems()` is not passed to `getNavigationArray()`.
This is a backport of the fix in https://github.com/concrete5/concrete5/pull/3769.

Fix for ignore excluded nav items still being excluded.

---

web/concrete/helpers/concrete/interface.php

Some constants are not defined at this point.
Fix #1968

Don't call getDashboardAndSearchMenus during install

---

web/concrete/core/models/permission/access/entity/types/page_owner.php

Always return an array from PageOwnerPermissionAccessEntity::getAccessEntityUsers()

---

web/concrete/core/models/attribute/key.php

In #1955 I forgot to add a magic method to support the deprecated `AttributeKey::add` (which has been renamed to `addAttributeKey` because of LSP problems).

Add magic method to support deprecated AttributeKey::add

---

web/concrete/core/helpers/validation/strings.php

emails addresses with a TLD longer than 3 characters are considered invalid, let's fix this.

fix email validation

---

web/concrete/tools/users/bulk_deactivate.php

The `$token` variable is called here https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/tools/users/bulk_deactivate.php#L37, but not initiated. It's good to know that the token is currently not outputted!
The `activate` tool file, however, does load it correctly: https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/tools/users/bulk_activate.php#L12

Add missing token variable in bulk_deactivate tool file

---

web/concrete/config/app.php

See discussion in issue #1986 - this should cover it? It is still possible to enable the search, but i think nobody ever did this because it was the default.

disable marketplace and newsflow integration by default #1986

---

web/concrete/core/models/permission/access/categories/custom/add_subpage.php
web/concrete/core/models/permission/access/categories/custom/edit_page_theme.php

This PR fixes the following error in PHP 7:
> Declaration of Concrete5_Model_EditPagePropertiesPagePermissionAccess::save($args) should be compatible with PermissionAccess::save($args = Array)

Call 'save' method with args

---

web/concrete/startup/process.php

In some cases the following error is triggered:
> Error Call to a member function getBlockTypeObject() on null
> /startup/process.php:68 require
It's when a user tries to rearrange blocks, but an incorrect block ID is sent in the AJAX request. 
Let's at least prevent this PHP error by checking for a valid object before calling `getBlockTypeObject`.

Check for Block object when arranging blocks

---

web/concrete/core/models/groups.php
web/concrete/core/models/search/group.php
web/concrete/core/models/user.php

Fixes instances I found of Groups mentioned in SQL statements
This pull request changes Groups to \`Groups\` in as many sql queries as I was able to find. I have confirmed the following works:
* logging in
* adding a new group
* adding a user to the group
* remove the user from a group
* deleting a group
I do not know if this has negative impacts for previous versions of mysql, but thought I would submit this as a pull request and reference #1980 in case anyone is looking for this type of fix

escape Groups for mysql 8

---

web/concrete/core/models/custom_style.php

The continue statements within a switch throw warnings that prevent custom styles from being used. 
In this context a break statement achieves the same purpose.

Change continue to break in custom_style.php
